In [2]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
b = np.array([[1],[2],[3],[4],[5]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [11]:
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)
print(c[0][2])

[[1 2 3]
 [4 5 6]]
(2, 3)
3


In [17]:
# Create array of zeros and ones 
a = np.zeros((3,3))
print(a)
 
b = np.ones((2,3))
print(b)

# array of some constants
c = np.full((3,2),5)
print(c)

#Identity matrix
d = np.eye(4)
print(d)

#random Matrix(return floats in half-open interval[0.0,1.0)
randomMatrix = np.random.random((2,3))
print(randomMatrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.52762998 0.87964241 0.00418815]
 [0.15871793 0.80369749 0.23921272]]


In [18]:
# print all 3rd column element
print(randomMatrix[ : ,2])

[0.00418815 0.23921272]


In [20]:
# make element as 1 of 2nd row 2nd column onwards
randomMatrix[1,1:] = 1 # Slicing
print(randomMatrix)

[[0.52762998 0.87964241 0.00418815]
 [0.15871793 1.         1.        ]]


In [26]:
# Set some rows and columns with any values
#Bydefault datatype are float so,we can change into int
z = np.zeros((3,3),dtype= np.int64)
print(z)
z[1, : ]=5
z[:,2]=7 # or z[:,-1]=7
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 7]
 [5 5 7]
 [0 0 7]]


In [27]:
#Datatypes
print(z.dtype)

int64


In [31]:
# Mathematical operation on numpy
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

#Element wise addition
print(x+y)
print(np.add(x,y))

#subtact
print(x-y)
print(np.subtract(x,y))


[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [37]:
#Multiply element wise
print(x*y)
print(np.multiply(x,y))

#divide
print(x/y)
print(np.divide(x,y))

#square root 
print(np.sqrt(x))
            

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [40]:
#Dot Product
print(x)
print(y)

print(x.dot(y))
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [42]:
# Multiplication(Dot product) of Vectors => scalar

a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a.dot(b))
print(np.dot(a,b))

30
30


In [43]:
print(a)

[1 2 3 4]


In [44]:
print(sum(a))

10


In [45]:
print(x)

[[1 2]
 [3 4]]


In [48]:
print(np.sum(x))
#print sum along downward axis(0)
print(np.sum(x,axis = 0))

#sum along axis=1
print(np.sum(x,axis = 1))

10
[4 6]
[3 7]


In [50]:
print(a)
b = b**2
print(b)

[1 2 3 4]
[ 1  4  9 16]


In [53]:
# stack of array
np.stack((a,b),axis=0) # along zero




array([[ 1,  2,  3,  4],
       [ 1,  4,  9, 16]])

In [55]:
a=np.stack((a,b),axis=1) #along 1

In [56]:

print(a)

[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]]


In [60]:
#Reshape a Numpy array
a = a.reshape((8,1))

print(a)

[[ 1]
 [ 1]
 [ 2]
 [ 4]
 [ 3]
 [ 9]
 [ 4]
 [16]]


In [61]:
a = a.reshape((-1,4))
print(a)

[[ 1  1  2  4]
 [ 3  9  4 16]]


In [64]:
#arange - generate certain number of element 

a = np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


## Numpy Random Module
- rand: Random values in a given shape.
- randn: return a sample (or samples) from the "Standard normal" distribution.
- randint: Return random integers from low(inclusive) to high(exclusive).
- random : return random floats in the half-open interval[0.0, 1.0)
- choice : Genrates a random sample from a given 1-d array
- shuffle: shuffles the contents of a sequence


In [81]:
np.random.shuffle(a)
print(a)

[6 9 5 8 5]


In [80]:
a = np.random.randn(2,3)
print(a)

a = np.random.randint(5,10,5)
print(a)

ele = np.random.choice([1,8,3,5,10,9])
print(ele)

b = np.random.rand(2,3)
print(b)

[[-1.17813522  0.42708687 -0.16558527]
 [ 0.51483695 -0.57239435  0.79466897]]
[5 9 5 8 6]
8
[[0.16405239 0.78758032 0.51863143]
 [0.98019684 0.90038052 0.12854697]]


In [102]:
x = [5,6,7,8]
np.random.seed(1) #use seed for generating random number in same order
np.random.shuffle(x)
print(x)

[8, 7, 5, 6]


## Some More Numpy Functions- statistics
- min, max
- mean
- median
- average
- variance
- standard deviation


In [110]:
a = np.array([[1,2,3,4],[7,6,5,0]])
print(a)
print(np.min(a))
# axis=0 - along cloumn we calculate
print(np.min(a,axis =0))
# axis=1 - along row we calculate
print(np.min(a,axis=1))

[[1 2 3 4]
 [7 6 5 0]]
0
[1 2 3 0]
[1 0]


In [115]:
#mean
b = np.array([1,2,3,4,5])
m = sum(b)/5
print(m)

print(np.mean(b))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

3.0
3.0
[4. 4. 4. 2.]
[2.5 4.5]


In [126]:
#median(arrange in increasing order then find middle)
c = np.array([1,5,4,2,0])
print(np.median(c))

#mean vs average is weighted
print(np.mean(c))

#weights
w = np.array([1,2,3,4,5])
print(np.average(c,weights=w))

wg = np.array([1,1,1,1,1])
print(np.average(c,weights = wg))

#standard Deviation
u = np.mean(c)
mystd = np.sqrt(np.mean(abs(c-u)**2))
print(mystd)

#Inbuilt function SD:
sdev = np.std(c)
print(sdev)

#variance
print(mystd**2)
#inbuilt
print(np.var(c))


2.0
2.4
2.066666666666667
2.4
1.854723699099141
1.854723699099141
3.440000000000001
3.4400000000000004


## Matrices and Tensor

In [137]:
#Tensor is an array with more than 2 axes, denoted as X
#Think of tensor as a generalization of an array with more than 2 axes

#Here X is a Matrix
X = np.array([[4,5,7],[10,11,13],[56,80,90]])
print(X.shape)
print(X)

print(X[1][1])
X[1:, :] = 2  #X[rs : re,cs:ce]=2
print(X)

(3, 3)
[[ 4  5  7]
 [10 11 13]
 [56 80 90]]
11
[[4 5 7]
 [2 2 2]
 [2 2 2]]


In [139]:
#Here T is a Tensor
T = np.array([[[4,5,7],[10,11,13]],[[56,80,90], [9,8,10]]])

print(T.shape)
print(T)

(2, 2, 3)
[[[ 4  5  7]
  [10 11 13]]

 [[56 80 90]
  [ 9  8 10]]]


In [141]:
#Transpose

x = np.array([[1,2],[5,6]])
print(x)
xt = np.transpose(x)
print(xt)

[[1 2]
 [5 6]]
[[1 5]
 [2 6]]


In [146]:
y = x.reshape((-1,1))
print(y)
print(np.transpose(y))
print(np.transpose(y).shape)

[[1]
 [2]
 [5]
 [6]]
[[1 2 5 6]]
(1, 4)


## Broadcasting 
- you can add a scalar to a vector, and numpy will add it to each element in the vector
  x + a = xi + a
    

In [147]:
l = [1,2,3,4]
l = np.array(l)
l = l+1
print(l)

[2 3 4 5]


In [149]:
v = [[1,2,3,4],[4,5,6,7]]
v = np.array(v)
v = v**2
print(v)
print(v+1)

[[ 1  4  9 16]
 [16 25 36 49]]
[[ 2  5 10 17]
 [17 26 37 50]]


In [150]:
np.sqrt(v)

array([[1., 2., 3., 4.],
       [4., 5., 6., 7.]])

In [153]:
## Matrix Multiplication
X = np.array([[4,5,7],[10,11,13],[56,80,90]])
Y = np.array([[40,50,70],[100,110,130],[560,800,900]])


In [155]:
print(X.shape)
print(Y.shape)

print(X)
print(Y)

(3, 3)
(3, 3)
[[ 4  5  7]
 [10 11 13]
 [56 80 90]]
[[ 40  50  70]
 [100 110 130]
 [560 800 900]]


In [156]:
product = np.dot(X,Y)
print(product)

[[ 4580  6350  7230]
 [ 8780 12110 13830]
 [60640 83600 95320]]


In [157]:
X = np.array([[4,5,7],[10,11,13],[56,80,90]])

Y = np.eye(3)
print(X)
print(Y)

[[ 4  5  7]
 [10 11 13]
 [56 80 90]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [158]:
print(X*Y)

[[ 4.  0.  0.]
 [ 0. 11.  0.]
 [ 0.  0. 90.]]


## Norms
- Norm can be thought of as a proxy for size of a vector.


In [5]:
x = np.array([-5,3,10])

In [7]:
lp2 = np.linalg.norm(x)
lp1 = np.linalg.norm(x,ord=1)
print(lp1)
print(lp2)

18.0
11.575836902790225


In [161]:
lpinf = np.linalg.norm(x,ord=np.inf)
print(lpinf)

10.0


In [3]:
y = np.array([[2,-2,1],[-1,2,-1],[2,-4,1]])

In [8]:
lpinfy = np.linalg.norm(y,ord=np.inf)
lp22 = np.linalg.norm(y)
print(lp22)
print(lpinfy)

6.0
7.0


In [9]:
A = np.array([[1,-3,4],[-2,10,-7],[0,1,0],[0,0,0]])
B = np.array([[5,0],[-2,11],[-3,12]])

In [10]:
print(A*B)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 