In [37]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [38]:
dfx = pd.read_csv("Diabetes_XTrain.csv")
dfy = pd.read_csv("Diabetes_YTrain.csv")
dfz = pd.read_csv("Diabetes_Xtest.csv")

In [39]:
#dfx.head(n=5)
dfz.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            0      180             90             26       90  36.5   
1            2       93             64             32      160  38.0   
2            2      114             68             22        0  28.7   
3           13       76             60              0        0  32.8   
4            1       80             74             11       60  30.0   

   DiabetesPedigreeFunction  Age  
0                     0.314   35  
1                     0.674   23  
2                     0.092   25  
3                     0.180   41  
4                     0.527   22

In [43]:
X = dfx.values
Y = dfy.values
Z = dfz.values

X = X[:,:]
Y = Y[:,:].reshape((-1,))
Z = Z[:,:]

print(X.shape)
print(Y.shape)
print(Z.shape)

print(Z)

(576, 8)
(576,)
(192, 8)
[[0.00e+00 1.80e+02 9.00e+01 ... 3.65e+01 3.14e-01 3.50e+01]
 [2.00e+00 9.30e+01 6.40e+01 ... 3.80e+01 6.74e-01 2.30e+01]
 [2.00e+00 1.14e+02 6.80e+01 ... 2.87e+01 9.20e-02 2.50e+01]
 ...
 [0.00e+00 1.62e+02 7.60e+01 ... 4.96e+01 3.64e-01 2.60e+01]
 [1.20e+01 8.40e+01 7.20e+01 ... 2.97e+01 2.97e-01 4.60e+01]
 [0.00e+00 9.40e+01 0.00e+00 ... 0.00e+00 2.56e-01 2.50e+01]]


In [44]:
def dist(x1,x2):
    return np.sqrt(sum((x1-x2)**2))

def knn(X,Y,queryPoint,k=5):
    
    vals = []
    m = X.shape[0]
    
    for i in range(m):
        d = dist(queryPoint,X[i])
        vals.append((d,Y[i]))
        
    vals = sorted(vals)
    # Nearest/first K points
    vals = vals[:k]
    
    vals = np.array(vals)
    
    #print(vals)
    new_vals = np.unique(vals[:,1],return_counts=True)
    #print(new_vals)
    
    index = new_vals[1].argmax()
    pre = new_vals[0][index]
    
    return pre

In [45]:
with open("Output.csv", "w") as file:
    header = ",".join(["Outcome"]) + "\n"
    file.write(header)
    
    n = Z.shape[0]
    for j in range(n):
        x = knn(X,Y,Z[j]);
        val = "".join([str(x)]) + "\n"
        file.write(val)
        
        
        
    
    